### ISSUE TITLE
do flakey latency tests point to a larger problem?

### ISSUE THREAD

**Issue by jpittis** [Shopify/toxiproxy#114]
https://github.com/Shopify/toxiproxy/pull/112 changes the maximum latency allowed in a test from `n + 10ms` to `n + 20ms`. Have these tests always been flakey? (I doubt it.)

If not, does this increase in latency affect all toxics or just the latency one. Why? (If it's just the latency toxic, then I think this issue can be closed.)

**Comment by xthexder** [comment]
I've only really seen the latency toxic tests fail, the noop latency has been consistent.
I think most of the failures are due to CircleCI load rather than toxiproxy problems, since I never see the failures locally.

Going to close this for now, Can discuss it more if we start seeing more flakey tests.
