### ISSUE TITLE
Provide -master docker images

### ISSUE THREAD

**Issue by kelvich** [Shopify/toxiproxy#142]
Currently :latest docker image is a build of 2.0.0 without /populate endpoint. It will be handy to have image of current -master.

**Comment by kelvich** [comment]
Also `docker build .` in master is failing due to missing dependency golang.org/x/crypto/ssh/terminal

**Comment by xthexder** [comment]
I've fixed the docker build failures on master, so you should be able to build your own containers now.
I don't want to start releasing master docker builds because anything in them can easily change by the time the next version is released, and I don't want to have to support release candidates and development versions.

You are welcome to build your own container off master, but just be prepared to make any necessary changes when upgrading to 2.1.0 if/when you do.
