### ISSUE TITLE
Is toxiproxy support https as upstream? 

### ISSUE THREAD

**Issue by xunwu** [Shopify/toxiproxy#173]
for example I want to use https://www.google.com as the upstream and listen on my local host. is that possible?

**Comment by xunwu** [comment]
I tried to post the proxy, but when I visit the localhost, it always say "unable to open the connection to upstream" any idea with that ?

**Comment by jpittis** [comment]
`HTTPS` works through toxiproxy. It will require additional client configuration so that the certificate is verified properly.

https://github.com/Shopify/toxiproxy/issues/175#issuecomment-301464691 provides an example of using curl as an `HTTPS` client through toxiproxy.

You'll want your upstream to not include the protocol. Use `www.google.com:443` rather than `https://www.google.com` as an upstream. Where `443` is the standard port for `HTTPS`.

Thanks for the question!

**Comment by dentarg** [comment]
Looks to me like this issue could be closed
