### ISSUE TITLE
Support for proxying HTTP to HTTPS

### ISSUE THREAD

**Issue by mmollaverdi** [Shopify/toxiproxy#175]
## Problem

I have some upstream APIs which run over https. Using toxyproxy to proxy https to https works fine, except that the local toxiproxy instances won't be responding with a valid SSL certificate, so over curl for example, I need to use the `-k` option:

```
$ toxiproxy-cli create https-to-https -l :9985 -u www.google.com:443
Created new proxy https-to-https

$ curl -H "Host: www.google.com" https://localhost:9985/
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

$ curl -H "Host: www.google.com" -k https://localhost:9985/
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com.au/?gfe_rd=cr&amp;ei=L1oFWaKgIZLp8we91LSwCw">here</A>.
</BODY></HTML>
```

This is hard to get around specially if you're using toxi-proxy to test the interactions between different APIs. The downstream APIs which talk to upstream dependencies through toxiproxy, need to disable SSL certificate verification. This is done differently depending on which programming language and which library that API uses.

## Suggestion

My suggestion is to implement support for proxying https requests through http, i.e. a toxi-proxy proxy can `listen`s over http, but communicates to `upstream` over https. One way to configure such proxies would be to include the desired protocol in both `listen` and `upstream` values, but there are probably other ways to achieve this too.

```
toxiproxy-cli create http-to-https -l http://localhost:9985 -u https://www.google.com:443
```

Note the inclusion of `http` in `-l` argument and `https` in `-u` above.
This doesn't seem to be supported currently.

Thoughts abut adding support for this or alternative solutions which would achieve this?

**Comment by jpittis** [comment]
Hey there, thanks for opening an issue. Sorry for the delayed reply.

I believe the culprit in the situation described is the `curl` `HTTPS` client. When doing certificate verification, `curl` needs to compare the host it's querying against the host in the certificate received. I assume `curl` is provided with an IP address and does not know that it is querying google through a proxy. This is why adding `-k` fixes the error which demonstrates the error is with the client rather than the server.

### Recreation / Example Solution

<img width="529" alt="screen shot 2017-05-15 at 8 41 52 am" src="https://cloud.githubusercontent.com/assets/5767836/26058117/6613fea2-394a-11e7-9604-099e15aa5f71.png">

If I add `www.google.com` to my `/etc/hosts` file so that it resolves to `127.0.0.1`, querying google from `curl` will now query the proxy instead.

<img width="260" alt="screen shot 2017-05-15 at 8 41 00 am" src="https://cloud.githubusercontent.com/assets/5767836/26058158/99f22fc8-394a-11e7-81f6-7ea9c08383f6.png">
<img width="671" alt="screen shot 2017-05-15 at 8 40 30 am" src="https://cloud.githubusercontent.com/assets/5767836/26058163/a03726fe-394a-11e7-86ad-346c86013605.png">

Notice that this time, even though the `HTTPS` request is indeed going through toxiproxy, the certificate is being verified properly. I believe this demonstrates that with a correctly configured client, `HTTPS` works fine through toxiproxy.

I don't know if `curl` has an flag to set the `host` being used for certificate validation.

**Comment by dentarg** [comment]
> I don't know if curl has an flag to set the host being used for certificate validation.

This seems to work for your setup above, but without any change to `/etc/hosts`

    curl -s -v --resolve 'www.google.com:6677:127.0.0.1' https://www.google.com:6677

https://curl.haxx.se/docs/manpage.html#--resolve

**Comment by jpittis** [comment]
Awesome thanks @dentarg. I'm closing this issue because I believe it's been resolved by the above comment. Please feel free to reopen it if you disagree @mmollaverdi.

**Comment by sirupsen** [comment]
@jpittis do you want to add a note to the README in the FAQ?

**Comment by matisoffn** [comment]
I'm trying to do something similarly, but with two important differences:

1. The request URL has a path in it
2. I'm not using cURL -- I'm using Faraday in Ruby.

Struggling to figure out how to do both here. Any insight?

**Comment by xthexder** [comment]
Toxiproxy doesn't know anything about the data it passes through the proxy. It is not protocol specific.

If you want to proxy https, you need to either have the request hostname match the proxy target somehow (like with `/etc/hosts` or `--resolve`), or disable certificate verification. This isn't secure, but for local proxies that shouldn't matter.

Another option would be to put something like nginx, or another http-specific proxy in front of the target server to handle ssl for you. That way all proxied connections can run on http instead.

**Comment by carpeliam** [comment]
> <img alt="screen shot 2017-05-15 at 8 41 52 am" width="529" src="https://cloud.githubusercontent.com/assets/5767836/26058117/6613fea2-394a-11e7-9604-099e15aa5f71.png">
> 
> If I add `www.google.com` to my `/etc/hosts` file so that it resolves to `127.0.0.1`, querying google from `curl` will now query the proxy instead.
> 
> <img alt="screen shot 2017-05-15 at 8 41 00 am" width="260" src="https://cloud.githubusercontent.com/assets/5767836/26058158/99f22fc8-394a-11e7-81f6-7ea9c08383f6.png">

@jpittis thanks for this reply, we were able to duplicate the same success you showed for google.com and other popular websites. However, we're running into one issue with a website (not publicly accessible) where we do the exact same thing as you're showing, but we get an `SSL_ERROR_SYSCALL` from curl. Can you think of any reason why that might be the case? Here are the verbose curl logs:

```sh
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to our.special.website.com (127.0.0.1) port 6677 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to our.special.website.com:6677
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to our.special.website.com:6677
```

**Comment by shashankjhs** [comment]
@carpeliam were you able find find solution to it

**Comment by shashankjhs** [comment]
@carpeliam were you able find find solution to this https issue

**Comment by shashankjhs** [comment]
@carpeliam were you able find find solution to this https issue
