### ISSUE TITLE
Regarding parameter to get the percentage of request that will be delayed

### ISSUE THREAD

**Issue by abecedarius** [Shopify/toxiproxy#239]
I have the toxiproxy wrapped around the restful service.
I have defined the latency and jitters to like mentioned below:
toxiproxy-cli-windows-amd64.exe toxic add assetproxy -t latency -n latencyassetproxy -a latency=1500 -a jitter=1000

I need to know if there is any parameter that will predict how much percentage of calls will be delay by how much time?
Or is there any calculation to convert this to the percentage of failures that will be caused when i run the load test on the client by putting the timeout value of 2 seconds on the client?

**Comment by xthexder** [comment]
You can see the delay calculation here: [latency.go](https://github.com/Shopify/toxiproxy/blob/master/toxics/latency.go)

Delay is calculated as `latency +/- jitter`, so in your example, the latency of any given piece of data would be a random amount between `500ms` and `2500ms`.
This would mean a ~25% chance your request would timeout after 2 seconds. Since Toxiproxy works with buffers, the chance could be slightly higher if your HTTP request gets split up between 2 buffers This is usually up to 32 KB, but is not guaranteed, and can be even smaller if the `slicer` toxic is used.

There is also the `toxicity` option, which can specify the percentage of connections affected by the latency toxic (which is per-connection, not per-buffer).

**Comment by abecedarius** [comment]
Thanks, I will try these options
