### ISSUE TITLE
Default host is localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by JesseEstum** [Shopify/toxiproxy#263]
Is there any interest in changing the default host value to `0.0.0.0` instead of `localhost`?

I feel that this would help "dummy-proof" running toxiproxy in a docker container.  As it stands now, docker containers do work fine due to this line in the Dockerfile: https://github.com/Shopify/toxiproxy/blob/cfe8289de2671d6e090c0632e67fca3ba54719ab/Dockerfile#L8 .

HOWEVER, In my personal use case I needed to override the `CMD` to pass in a `-config` argument to the toxiproxy container.  This had the side effect of otherwise breaking proxy network traffic into/out of the container because the toxiproxy host bind changed from `0.0.0.0` to `localhost`.  Effectively this means that if someone wants to use docker and pass `-config /my/config.json` they must also pass `-host=0.0.0.0`.

Changing the default behavior to bind to `0.0.0.0` should make this a little more user friendly while continuing to work well in the non-container environment.

If this is of interest, let me know and I'll open up a PR for the change.

Thanks!

**Comment by xthexder** [comment]
The problem with listening on 0.0.0.0 by default is mostly because of security.
Because toxiproxy is unauthenticated, listening on a public interface means that anyone on your network could create new proxies on your machine.
This would make it trivial to spoof traffic coming from your machine, and could potentially give them access to sensitive information, like local databases that would normally be behind a firewall / only listening locally.

This isn't as big an issue within Docker, since ports need to be bound explicitly in order to listen on external interfaces.
While it's a big of an inconvenience, I think toxiproxy should default to the more-safe localhost address.
