### ISSUE TITLE
Prometheus metrics usage question

### ISSUE THREAD

**Issue by jgrimm3** [Shopify/toxiproxy#393]
We would like to have toxiproxy incorporated into a standalone test bed. The traffic of two instances of an application will pass through the proxy. We would like to apply toxics, gather metrics and graph those metrics and tie them into a web front end. New to toxiproxy and to prometheus.

Do we have to use the GO client to use the Prometheus metrics? 
Do we have to configure anything internally to enable collection of the metrics or simply supply the metrics flag?
Do we run the toxic command with the flag, and the retrieve the metrics at /metrics through the API?

does "Prometheus-compatible" metrics mean we can then directly ingest them into prometheus? or can we even directly pass them to grafana?

Any diagrams or scenarious would be greatly appreciated.
Thank you!

**Comment by neufeldtech** [comment]
Hi @jgrimm3 ,

A bit of background here on the layout of things, which will hopefully answer some of your questions.

Prometheus has a scrape metrics collection model, where it will make HTTP calls to configured endpoints in order to ingest metrics from them. By convention, the URI path that is commonly used among application servers to expose prometheus metrics is `/metrics`, and when visiting a raw metrics URL in a browser, it would look something like this:

http://demo.robustperception.io:9100/metrics

```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 4.3946e-05
go_gc_duration_seconds{quantile="0.25"} 5.858e-05
go_gc_duration_seconds{quantile="0.5"} 6.3656e-05
go_gc_duration_seconds{quantile="0.75"} 7.1047e-05
go_gc_duration_seconds{quantile="1"} 0.000186657
go_gc_duration_seconds_sum 479.315664448
go_gc_duration_seconds_count 6.453589e+06
.... etc
```

In recent releases, we've configured some minimal prometheus support in Toxiproxy. That is to say that when booting toxiproxy with extra flags, the route `/metrics` would return plaintext prometheus metrics (similar to what is shown in the sample above).

We've configured two different cli switches to enable turning on/off different types of metrics exposition, this is just to give the user finite control and allow them to 'opt in' to this feature, rather than having it on by default.

As shown [Here](https://github.com/Shopify/toxiproxy/blob/5cfb64cb61e494c0e0ef2e45deb3df94da892102/METRICS.md), when booting Toxiproxy with the `-proxy-metrics` flag, the app will expose internal business-logic metrics about number of bytes passing through each proxy. When booted with `-runtime-metrics`, the app will expose golang runtime-related metrics (cpu usage, garbage collection stats, memory usage, etc) from the golang runtime. Of course, it would be common to run with both of these flags at the same time to get all available metrics.

A typical setup would be something like this:

- Prometheus server (Configured to scrape your toxiproxy node at 1.2.3.4:8474/metrics)
- Toxiproxy server (Configured to expose metrics, i.e. `./toxiproxy-server -runtime-metrics -proxy-metrics`
- Grafana configured with a prometheus data source which points to your prometheus server

All that being said, the actual metrics that Toxiproxy exposes right now are fairly limited, and exist to solve one single use case that we've had where we wanted to know via prometheus if bytes were flowing through a proxy or not. More metrics may be added in the future.

Let me know if you still have further questions.
